name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache SDK and Toolchain
        uses: actions/cache@v4
        with:
          path: |
            build/app
            build/innoextract.exe
            build/tc32
            build/tl_zigbee_sdk
          key: |
            toolchain-linux-${{ hashFiles('build/tc32') }}
          restore-keys: |
            toolchain-linux
          save-always: true

      - name: Install SDK and Toolchain
        run: |
          mkdir -p build
          cd build
          cmake -P ../cmake/TelinkSDK_Linux.cmake

      - name: Build
        run: |
          cmake -B build
          cmake --build build

      - name: Archive switch files
        uses: actions/upload-artifact@v4
        with:
          name: switch-linux
          path: |
            build/switch/switch*
            build/switch/*switch.zigbee
            !build/**/*.lst

      - name: Archive light files
        uses: actions/upload-artifact@v4
        with:
          name: light-linux
          path: |
            build/light/light*
            build/light/*light.zigbee
            !build/**/*.lst

      - name: Archive IASsensor files
        uses: actions/upload-artifact@v4
        with:
          name: IASsensor-linux
          path: |
            build/IASsensor/IASsensor*
            build/IASsensor/*IASsensor.zigbee
            !build/**/*.lst
