name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Repository Structure
        run: |
          echo "Checking Repository Structure..."
          ls -R ${{ github.workspace }}/cmake || echo "⚠️ cmake directory not found!"

      - name: Verify CMake File
        run: |
          if [ ! -f ${{ github.workspace }}/cmake/TelinkSDK_Mac.cmake ]; then
            echo "❌ Error: TelinkSDK_Mac.cmake not found!"
            exit 1
          fi

      - name: Install Dependencies
        run: |
          brew install --formula ninja cmake

      - name: Restore Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            build/app
            build/innoextract.exe
            build/tc32
            build/tl_zigbee_sdk
          key: toolchain-macos-${{ hashFiles('build/tc32') }}
          restore-keys: toolchain-macos

      - name: Install SDK and Toolchain
        run: |
          mkdir -p build
          cd build
          if [ ! -f ../cmake/TelinkSDK_Mac.cmake ]; then
            echo "⚠️ Warning: TelinkSDK_Mac.cmake not found before installation."
          fi
          cmake -P ../cmake/TelinkSDK_Mac.cmake
          ls -R ../cmake/

      - name: Build
        run: |
          cmake -B build
          cmake --build build

      - name: Save Cache
        uses: actions/cache/save@v4
        with:
          path: |
            build/app
            build/innoextract.exe
            build/tc32
            build/tl_zigbee_sdk
          key: toolchain-macos-${{ hashFiles('build/tc32') }}

      - name: Archive switch files
        uses: actions/upload-artifact@v4
        with:
          name: switch-macos
          path: |
            build/switch/switch*
            build/switch/*switch.zigbee
            !build/**/*.lst

      - name: Archive light files
        uses: actions/upload-artifact@v4
        with:
          name: light-macos
          path: |
            build/light/light*
            build/light/*light.zigbee
            !build/**/*.lst

      - name: Archive IASsensor files
        uses: actions/upload-artifact@v4
        with:
          name: IASsensor-macos
          path: |
            build/IASsensor/IASsensor*
            build/IASsensor/*IASsensor.zigbee
            !build/**/*.lst
